/*
    VALEURS DE DEPART LORS DE LA CREATION DE LA CARTE
*/
#DEFINE nb_gaulois_depart 5
#DEFINE nb_gauloises_depart 5
#DEFINE nb_sangliers_depart 5
#DEFINE nb_arbres_depart 5

/*
    TAILLE DE LA MAP
*/
#DEFINE LARGEUR_CARTE 15
#DEFINE HAUTEUR_CARTE 15
#DEFINE OUEST_CARTE 15
#DEFINE EST_CARTE 0
#DEFINE SUD_CARTE 0
#DEFINE NORD_CARTE 15
