/*
    VALEURS DE DEPART LORS DE LA CREATION DE LA CARTE
*/
#define NB_GAULOIS_DEPART 5
#define NB_GAULOISES_DEPART 5
#define NB_SANGLIERS_DEPART 5
#define NB_ARBRES_DEPART 5

/*
    TAILLE DE LA MAP
*/
#define LARGEUR_CARTE 15
#define HAUTEUR_CARTE 15
#define OUEST_CARTE 15
#define EST_CARTE 0
#define SUD_CARTE 0
#define NORD_CARTE 15
